// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiWsUq_X_GLCd5epHj3pleMK_9JgXDWk8',
    appId: '1:1095875882185:web:eda81585799f05263d7118',
    messagingSenderId: '1095875882185',
    projectId: 'nerala-v1',
    authDomain: 'nerala-v1.firebaseapp.com',
    storageBucket: 'nerala-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTXocSdzAv9hk5wbXRrzg4TDBkDoRTpY',
    appId: '1:1095875882185:android:2023e43fc91c3a403d7118',
    messagingSenderId: '1095875882185',
    projectId: 'nerala-v1',
    storageBucket: 'nerala-v1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABemJp9JXrxyODTHH0bufYk4ufuU66YcM',
    appId: '1:1095875882185:ios:331654bdfbb2b3cb3d7118',
    messagingSenderId: '1095875882185',
    projectId: 'nerala-v1',
    storageBucket: 'nerala-v1.firebasestorage.app',
    iosBundleId: 'com.example.otherScreens',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABemJp9JXrxyODTHH0bufYk4ufuU66YcM',
    appId: '1:1095875882185:ios:331654bdfbb2b3cb3d7118',
    messagingSenderId: '1095875882185',
    projectId: 'nerala-v1',
    storageBucket: 'nerala-v1.firebasestorage.app',
    iosBundleId: 'com.example.otherScreens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiWsUq_X_GLCd5epHj3pleMK_9JgXDWk8',
    appId: '1:1095875882185:web:aefe77c1d9b54f003d7118',
    messagingSenderId: '1095875882185',
    projectId: 'nerala-v1',
    authDomain: 'nerala-v1.firebaseapp.com',
    storageBucket: 'nerala-v1.firebasestorage.app',
  );

}